### ISSUE TITLE
No such file or directory: 'models/jvrc_mj_description/xml/scene.xml'

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [rohanpsingh/LearningHumanoidWalking#10]
When I train this repository, the follwing error occurred.

```
python3 run_experiment.py train --logdir log --num_procs 4 --env jvrc_walk
Wrapping in SymmetricEnv.
Modifying XML model...
Traceback (most recent call last):
  File "run_experiment.py", line 121, in <module>
    run_experiment(args)
  File "run_experiment.py", line 36, in run_experiment
    mirrored_obs=env_fn().robot.mirrored_obs,
  File "/home/dl/Humanoid/LearningHumanoidWalking/envs/jvrc/jvrc_walk.py", line 22, in __init__
    builder(path_to_xml_out)
  File "/home/dl/Humanoid/LearningHumanoidWalking/envs/jvrc/gen_xml.py", line 12, in builder
    mjcf_model = mjcf.from_path(JVRC_DESCRIPTION_PATH)
  File "/home/dl/Humanoid/Humanoid/lib/python3.8/site-packages/dm_control/mjcf/parser.py", line 102, in from_path
    contents = resources.GetResource(path)
  File "/home/dl/Humanoid/Humanoid/lib/python3.8/site-packages/dm_control/utils/io.py", line 22, in GetResource
    with open(name, mode=mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models/jvrc_mj_description/xml/scene.xml'
```
Please let me know how to fix it.

**Comment by rohanpsingh** [comment]
Hi, it seems you don't have the submodule in your path. Did you clone with the `--recurse-submodules` ?

**Comment by Ishihara-Masabumi** [comment]
Thanks, it is going well.
BTW, please tell me the following message item meanings.

- Return (batch) 
- Mean Eplen
- Clip Fraction

Are the following losses are the less the better?
- Actor loss, Critic loss, Mirror loss

Are the following values are the greater the better?
- Mean KL Div, Mean Entropy

Best regards,

**Comment by rohanpsingh** [comment]
It's difficult to explain the meaning of each term, I recommend you to check out [Stable-Baselines](https://github.com/DLR-RM/stable-baselines3/) for a better documentation. In general, losses should go down. Mean entropy should remain constant. In my case, I don't monitor each item carefully. Most importantly, the return and the ep_len should go up!
