### ISSUE TITLE
azimuth' is not a valid attribute for <global>

### ISSUE THREAD

**Issue by skr3178** [rohanpsingh/LearningHumanoidWalking#34]
i have copied the jvrc_mj_description model from the commit proposed within this repo. It didn't get downloaded with the rest of the repo.

`python3 run_experiment.py train --logdir exp_dir --num_procs 12 --env jvrc_step
Wrapping in SymmetricEnv.
Modifying XML model...
Warning! Cannot use SymmetricEnv. Line 8: error while parsing element <global>: 'azimuth' is not a valid attribute for <global>
Modifying XML model...
Traceback (most recent call last):
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/parser.py", line 213, in _parse_children
    mjcf_child.set_attributes(**attributes)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/element.py", line 534, in set_attributes
    old_value = self._get_attribute(attribute_name)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/element.py", line 507, in _get_attribute
    self._check_valid_attribute(attribute_name)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/element.py", line 504, in _check_valid_attribute
    attribute_name, self._spec.name))
AttributeError: 'azimuth' is not a valid attribute for <global>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_experiment.py", line 121, in <module>
    run_experiment(args)
  File "run_experiment.py", line 41, in run_experiment
    obs_dim = env_fn().observation_space.shape[0]
  File "/home/sangramrout/LearningHumanoidWalking/envs/jvrc/jvrc_step.py", line 22, in __init__
    builder(path_to_xml_out)
  File "/home/sangramrout/LearningHumanoidWalking/envs/jvrc/gen_xml.py", line 12, in builder
    mjcf_model = mjcf.from_path(JVRC_DESCRIPTION_PATH)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/parser.py", line 106, in from_path
    assets=assets)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/parser.py", line 169, in _parse
    _parse_children(xml_root, mjcf_root, escape_separators)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/parser.py", line 219, in _parse_children
    _parse_children(xml_child, mjcf_child, escape_separators)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/parser.py", line 218, in _parse_children
    f'<{xml_child.tag}>: {err}').with_traceback(traceback)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/parser.py", line 213, in _parse_children
    mjcf_child.set_attributes(**attributes)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/element.py", line 534, in set_attributes
    old_value = self._get_attribute(attribute_name)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/element.py", line 507, in _get_attribute
    self._check_valid_attribute(attribute_name)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/element.py", line 504, in _check_valid_attribute
    attribute_name, self._spec.name))
AttributeError: Line 8: error while parsing element <global>: 'azimuth' is not a valid attribute for <global>`

`python3 run_experiment.py train --logdir exp_dir --num_procs 12 --env jvrc_walk
Wrapping in SymmetricEnv.
Modifying XML model...
Warning! Cannot use SymmetricEnv. Line 8: error while parsing element <global>: 'azimuth' is not a valid attribute for <global>
Modifying XML model...
Traceback (most recent call last):
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/parser.py", line 213, in _parse_children
    mjcf_child.set_attributes(**attributes)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/element.py", line 534, in set_attributes
    old_value = self._get_attribute(attribute_name)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/element.py", line 507, in _get_attribute
    self._check_valid_attribute(attribute_name)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/element.py", line 504, in _check_valid_attribute
    attribute_name, self._spec.name))
AttributeError: 'azimuth' is not a valid attribute for <global>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_experiment.py", line 121, in <module>
    run_experiment(args)
  File "run_experiment.py", line 41, in run_experiment
    obs_dim = env_fn().observation_space.shape[0]
  File "/home/sangramrout/LearningHumanoidWalking/envs/jvrc/jvrc_walk.py", line 22, in __init__
    builder(path_to_xml_out)
  File "/home/sangramrout/LearningHumanoidWalking/envs/jvrc/gen_xml.py", line 12, in builder
    mjcf_model = mjcf.from_path(JVRC_DESCRIPTION_PATH)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/parser.py", line 106, in from_path
    assets=assets)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/parser.py", line 169, in _parse
    _parse_children(xml_root, mjcf_root, escape_separators)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/parser.py", line 219, in _parse_children
    _parse_children(xml_child, mjcf_child, escape_separators)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/parser.py", line 218, in _parse_children
    f'<{xml_child.tag}>: {err}').with_traceback(traceback)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/parser.py", line 213, in _parse_children
    mjcf_child.set_attributes(**attributes)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/element.py", line 534, in set_attributes
    old_value = self._get_attribute(attribute_name)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/element.py", line 507, in _get_attribute
    self._check_valid_attribute(attribute_name)
  File "/home/sangramrout/mambaforge/envs/rl/lib/python3.7/site-packages/dm_control/mjcf/element.py", line 504, in _check_valid_attribute
    attribute_name, self._spec.name))
AttributeError: Line 8: error while parsing element <global>: 'azimuth' is not a valid attribute for <global>`

**Comment by skr3178** [comment]
recreated a new env and this issue is gone
